'use client'
import {useState} from 'react'
import {useWs,USERS,days,fmt,due,ago,TODAY} from '@/lib/store'
import {Card,Chip,Empty,Stat,Bar,Head} from './ui'
import AIWidget from './AIWidget'
const ST:any={todo:['To do','mute'],progress:['In progress','accent'],blocked:['Blocked','bad'],done:['Completed','ok']}
const PR:any={high:'warn',medium:'accent',low:'mute'}
const Th=({c}:{c:string})=><th className="px-3 py-2 text-left font-medium text-mute">{c}</th>
function Updates({n=4}:{n?:number}){const {data}=useWs();return <Card title="Recent updates">{data.activity.length?<ul className="space-y-3">{data.activity.slice(0,n).map((a:any,i:number)=><li key={i} className="flex justify-between gap-3"><span><b className="font-medium">{a.who}</b> {a.what} <span className="text-mute">{a.target}</span></span><span className="shrink-0 text-xs text-mute">{ago(a.min)}</span></li>)}</ul>:<Empty title="No updates yet" hint="Uploads and comments from your projects will appear here."/>}</Card>}
function Projects(){const {data}=useWs();return <Card title="Active projects">{data.projects.length?<div className="divide-y divide-line">{data.projects.map((p:any)=><div key={p.name} className="py-3 first:pt-0 last:pb-0"><div className="mb-2 flex items-center justify-between"><span className="font-medium">{p.name} <span className="font-normal text-mute">{p.sub}</span></span><Chip tone={p.tone}>{p.status}</Chip></div><Bar pct={p.pct} tone={p.tone}/><p className="mt-1.5 text-xs text-mute">{p.pct}% complete. Lead {p.lead}, {p.team} members. Next: {p.milestone}</p></div>)}</div>:<Empty title="No active projects" hint="Projects you belong to will show up here."/>}</Card>}

export function Employee(){
 const {tasks,setStatus}=useWs();const mine=tasks.filter((t:any)=>t.assignee===USERS.employee)
 const pending=mine.filter((t:any)=>t.status!=='done').sort((a:any,b:any)=>a.due.localeCompare(b.due));const ongoing=mine.filter((t:any)=>t.status==='progress')
 const soon=pending.filter((t:any)=>days(t.due)<=7).length
 return <div className="fade"><Head title={`Good morning, ${USERS.employee}`} sub={soon?`${soon} of your tasks are due within a week.`:'You have nothing due in the next week.'}/>
 <div className="grid gap-4 lg:grid-cols-3"><div className="space-y-4 lg:col-span-2">
  <Card title="Pending tasks">{pending.length?<div className="-m-4 overflow-x-auto"><table className="w-full"><thead><tr className="border-b border-line"><Th c="Task"/><Th c="Priority"/><Th c="Due"/><Th c="Status"/></tr></thead><tbody>{pending.map((t:any)=>{const [d,tone]=due(t.due);return <tr key={t.id} className="border-b border-line last:border-0"><td className="px-3 py-2.5"><p className="font-medium">{t.title}</p><p className="text-xs text-mute">{t.project}{t.reason&&` · ${t.reason}`}</p></td><td className="px-3"><Chip tone={PR[t.priority]}>{t.priority}</Chip></td><td className="px-3"><Chip tone={tone as string}>{d}</Chip></td><td className="px-3"><select aria-label={`Status of ${t.title}`} className="field py-1" value={t.status} onChange={e=>setStatus(t.id,e.target.value)}>{Object.keys(ST).map(k=><option key={k} value={k}>{ST[k][0]}</option>)}</select></td></tr>})}</tbody></table></div>:<Empty title="You're all caught up" hint="Completed tasks are cleared from this list. New assignments will appear here."/>}</Card>
  <Card title="Ongoing tasks">{ongoing.length?<ul className="space-y-4">{ongoing.map((t:any)=><li key={t.id}><div className="mb-1.5 flex justify-between gap-3"><span className="font-medium">{t.title} <span className="font-normal text-mute">{t.project}</span></span><span className="text-mute">{t.progress}%</span></div><p className="mb-1.5 text-xs text-mute">{t.desc}</p><Bar pct={t.progress}/></li>)}</ul>:<Empty title="Nothing in progress" hint="Set a task to In progress and it will show up here with its progress."/>}</Card></div>
 <div className="space-y-4"><Updates/><Projects/><AIWidget/></div></div></div>}

export function Manager(){
 const {tasks,data}=useWs();const [win,setWin]=useState(7)
 const counts=Object.keys(ST).map(k=>({k,n:tasks.filter((t:any)=>t.status===k).length}));const max=Math.max(...counts.map(c=>c.n),1)
 const crit=tasks.filter((t:any)=>t.status!=='done'&&days(t.due)<=win).sort((a:any,b:any)=>a.due.localeCompare(b.due))
 const team=['Swapnil','Anamitra'].map(n=>({n,r:data.people.find((p:any)=>p.name===n).role,a:tasks.filter((t:any)=>t.assignee===n&&t.status!=='done').length}))
 return <div className="fade"><Head title={`Good morning, ${USERS.manager}`} sub={`${tasks.filter((t:any)=>t.status!=='done').length} open tasks across ${data.projects.length} projects.`}/>
 <div className="grid gap-4 lg:grid-cols-3"><div className="space-y-4 lg:col-span-2">
  <Card title="Workload by status"><div className="flex h-44 items-end gap-6 px-2">{counts.map(c=><div key={c.k} className="flex h-full flex-1 flex-col justify-end text-center"><span className="mb-1 font-semibold">{c.n}</span><div className="rounded-t" style={{height:`${c.n/max*80}%`,minHeight:c.n?4:2,background:`var(--${ST[c.k][1]})`,transition:'height .4s ease'}}/><span className="mt-2 text-xs text-mute">{ST[c.k][0]}</span></div>)}</div></Card>
  <Card title="Active projects"><div className="-m-4 overflow-x-auto"><table className="w-full"><thead><tr className="border-b border-line"><Th c="Project"/><Th c="Progress"/><Th c="Status"/><Th c="Lead"/><Th c="Deadline"/></tr></thead><tbody>{data.projects.map((p:any)=><tr key={p.name} className="border-b border-line last:border-0"><td className="px-3 py-2.5 font-medium">{p.name}</td><td className="w-40 px-3"><Bar pct={p.pct} tone={p.tone}/></td><td className="px-3"><Chip tone={p.tone}>{p.status}</Chip></td><td className="px-3">{p.lead}</td><td className="px-3">{fmt(p.deadline)}</td></tr>)}</tbody></table></div></Card>
  <Updates/></div>
 <div className="space-y-4">
  <Card title="Critical deadlines" action={<div className="flex gap-1">{[[7,'This week'],[31,'This month']].map(([w,l]:any)=><button key={w} onClick={()=>setWin(w)} className={`rounded px-2 py-1 text-xs ${win===w?'bg-accent text-white dark:text-[#07101f]':'text-mute hover:text-ink'}`}>{l}</button>)}</div>}>{crit.length?<ul className="space-y-3">{crit.map((t:any)=>{const [d,tone]=due(t.due);return <li key={t.id} className="flex justify-between gap-3"><span>{t.title}<span className="block text-xs text-mute">{t.assignee}, {t.project}</span></span><Chip tone={tone as string}>{d}</Chip></li>})}</ul>:<Empty title="Nothing due" hint={`No open tasks are due ${win===7?'this week':'this month'}.`}/>}</Card>
  <Card title="Your team"><table className="w-full"><thead><tr><Th c="Employee"/><Th c="Open tasks"/></tr></thead><tbody>{team.map(m=><tr key={m.n} className="border-t border-line"><td className="px-3 py-2"><p className="font-medium">{m.n}</p><p className="text-xs text-mute">{m.r}</p></td><td className="px-3">{m.a}</td></tr>)}</tbody></table></Card>
  <AIWidget/></div></div></div>}

export function HR(){
 const {data}=useWs();const [q,setQ]=useState(''),[dept,setDept]=useState('All'),[leave,setLeave]=useState<any[]>(data.leave)
 const depts=['All',...Array.from(new Set(data.people.map((p:any)=>p.dept)))] as string[]
 const rows=data.people.filter((p:any)=>(dept==='All'||p.dept===dept)&&p.name.toLowerCase().includes(q.trim().toLowerCase()))
 return <div className="fade"><Head title={`Good morning, ${USERS.hr}`} sub={`${leave.length} leave ${leave.length===1?'request needs':'requests need'} a decision.`}/>
 <div className="mb-4 grid grid-cols-2 gap-4 lg:grid-cols-4"><Stat label="Headcount" value={data.people.length}/><Stat label="On leave today" value={data.people.filter((p:any)=>p.status==='On leave').length}/><Stat label="Pending requests" value={leave.length}/><Stat label="Joining soon" value={data.joiners.length} note="Next 2 weeks"/></div>
 <div className="grid gap-4 lg:grid-cols-3"><Card className="lg:col-span-2" title="Employee directory" action={<div className="flex gap-2"><input className="field w-40" placeholder="Search name..." value={q} onChange={e=>setQ(e.target.value)} aria-label="Search employees"/><select className="field" value={dept} onChange={e=>setDept(e.target.value)} aria-label="Department">{depts.map(d=><option key={d}>{d}</option>)}</select></div>}>
  {rows.length?<div className="-m-4 overflow-x-auto"><table className="w-full"><thead><tr className="border-b border-line"><Th c="Name"/><Th c="Department"/><Th c="Location"/><Th c="Joined"/><Th c="Status"/></tr></thead><tbody>{rows.map((p:any)=><tr key={p.name} className="border-b border-line last:border-0"><td className="px-3 py-2.5"><p className="font-medium">{p.name}</p><p className="text-xs text-mute">{p.role}</p></td><td className="px-3">{p.dept}</td><td className="px-3">{p.city}</td><td className="px-3">{fmt(p.joined)} {p.joined.slice(0,4)}</td><td className="px-3"><Chip tone={p.status==='Active'?'ok':'warn'}>{p.status}</Chip></td></tr>)}</tbody></table></div>:<Empty dashed title="No employees found." hint="Try adjusting your search query."/>}</Card>
 <div className="space-y-4"><Card title="Leave requests">{leave.length?<ul className="space-y-3">{leave.map((l:any)=><li key={l.id}><p className="font-medium">{l.name} <span className="font-normal text-mute">{l.type}</span></p><p className="text-xs text-mute">{fmt(l.from)} to {fmt(l.to)}</p><div className="mt-1.5 flex gap-2"><button onClick={()=>setLeave(leave.filter(x=>x.id!==l.id))} className="rounded bg-accent px-2.5 py-1 text-xs font-medium text-white dark:text-[#07101f]">Approve</button><button onClick={()=>setLeave(leave.filter(x=>x.id!==l.id))} className="rounded border border-line px-2.5 py-1 text-xs">Decline</button></div></li>)}</ul>:<Empty title="No pending requests" hint="New leave requests will appear here for approval."/>}</Card>
 <Card title="Joining soon">{data.joiners.length?<ul className="space-y-2">{data.joiners.map((j:any)=><li key={j.name} className="flex justify-between"><span>{j.name} <span className="text-mute">{j.role}</span></span><span className="text-mute">{fmt(j.start)}</span></li>)}</ul>:<Empty title="No new joiners" hint="Upcoming start dates will be listed here."/>}</Card><AIWidget/></div></div></div>}

export function Executive(){
 const {tasks,data}=useWs();const e=data.exec,r=e.revenue,tot=(m:any)=>m.product+m.services+m.sales,last=tot(r[2]),prev=tot(r[1]),mx=Math.max(...r.map(tot))
 const od=tasks.filter((t:any)=>t.status!=='done'&&days(t.due)<0);const tone=e.score>=7?'bad':e.score>=4?'warn':'ok'
 return <div className="fade"><Head title={`Good morning, ${USERS.executive}`} sub="Company overview as of 6 October 2026."/>
 <div className="grid gap-4 lg:grid-cols-3"><div className="space-y-4 lg:col-span-2">
  <Card title="Weekly company summary" action={<Chip tone="accent">AI generated</Chip>}><ul className="list-disc space-y-2 pl-5">{e.summary.map((s:string)=><li key={s}>{s}</li>)}</ul></Card>
  <Card title="Risks that need action">{e.risks.length?<ul className="divide-y divide-line">{e.risks.map((k:any)=><li key={k.title} className="py-3 first:pt-0 last:pb-0"><div className="flex items-center gap-2"><Chip tone={k.tone}>{k.level}</Chip><span className="font-medium">{k.title}</span></div><p className="mt-1">{k.detail}</p><p className="text-xs text-mute">{k.dept}. Next step: {k.next}</p></li>)}</ul>:<Empty title="No open risks" hint="Risks flagged by your teams or contracts will be listed here."/>}</Card>
  <div className="grid gap-4 md:grid-cols-2">
   <Card title="Overdue items">{od.length?<ul className="space-y-2">{od.map((t:any)=><li key={t.id}>{t.title}<span className="block text-xs text-bad">{-days(t.due)} days overdue, {t.assignee}</span></li>)}</ul>:<Empty title="Nothing overdue" hint="Late tasks across the company will appear here."/>}</Card>
   <Card title="Contract alerts">{e.contracts.length?<ul className="space-y-2">{e.contracts.map((c:any)=><li key={c.name}><p className="font-medium">{c.name}</p><p className="text-xs text-mute">{c.note}. Due in {days(c.due)} days.</p></li>)}</ul>:<Empty title="No contract alerts" hint="Renewals and flagged clauses will appear here."/>}</Card></div></div>
 <div className="space-y-4">
  <Card title="Overall risk score"><svg viewBox="0 0 200 115" className="mx-auto w-56" role="img" aria-label={`Risk score ${e.score} out of 10`}><path d="M20 100A80 80 0 0 1 180 100" pathLength="100" fill="none" stroke="var(--line)" strokeWidth="14" strokeLinecap="round"/><path d="M20 100A80 80 0 0 1 180 100" pathLength="100" fill="none" stroke={`var(--${tone})`} strokeWidth="14" strokeLinecap="round" strokeDasharray={`${e.score*10} 100`}/><text x="100" y="92" textAnchor="middle" fontSize="30" fontWeight="600" fill="var(--ink)">{e.score}/10</text></svg><p className="text-center text-mute">Moderate risk</p></Card>
  <div className="grid grid-cols-2 gap-4"><Stat label="Revenue (Sep)" value={`$${last}k`} note={`+${((last-prev)/prev*100).toFixed(1)}% vs Aug`}/><Stat label="Compliance" value={`${e.compliance}%`}/></div>
  <Card title="Revenue by business unit"><div className="flex h-40 items-end gap-5">{r.map((m:any)=><div key={m.m} className="flex h-full flex-1 flex-col justify-end text-center"><div className="flex flex-col-reverse overflow-hidden rounded-t" style={{height:`${tot(m)/mx*85}%`}}><div className="bg-accent" style={{flex:m.product}}/><div className="bg-accent/60" style={{flex:m.services}}/><div className="bg-accent/30" style={{flex:m.sales}}/></div><span className="mt-2 text-xs text-mute">{m.m}</span></div>)}</div>
  <p className="mt-3 flex gap-4 text-xs text-mute"><span><i className="mr-1 inline-block size-2 bg-accent"/>Product</span><span><i className="mr-1 inline-block size-2 bg-accent/60"/>Services</span><span><i className="mr-1 inline-block size-2 bg-accent/30"/>Sales</span></p></Card>
  <AIWidget/></div></div></div>}
