'use client'
import {ReactNode} from 'react'
export const Logo=({mark=false,className=''}:{mark?:boolean;className?:string})=>{const n=mark?'logo-mark':'logo';return<><img src={`/${n}.png`} alt="HeimDall" className={`dark:hidden ${className}`}/><img src={`/${n}-light.png`} alt="HeimDall" className={`hidden dark:block ${className}`}/></>}
export const Card=({title,action,children,className=''}:{title:string;action?:ReactNode;children:ReactNode;className?:string})=><section className={`rounded-md border border-line bg-surface ${className}`}><header className="flex min-h-12 items-center justify-between gap-3 border-b border-line px-4 py-2.5"><h2 className="font-semibold">{title}</h2>{action}</header><div className="p-4">{children}</div></section>
export const Chip=({tone='mute',children}:{tone?:string;children:ReactNode})=><span className="chip" style={{['--c' as any]:`var(--${tone})`}}>{children}</span>
export const Empty=({title,hint,dashed=false}:{title:string;hint:string;dashed?:boolean})=><div className={`rounded-md px-4 py-8 text-center ${dashed?'border border-dashed border-line':''}`}><p className="font-medium">{title}</p><p className="mx-auto mt-1 max-w-xs text-mute">{hint}</p></div>
export const Stat=({label,value,note}:{label:string;value:ReactNode;note?:string})=><div className="rounded-md border border-line bg-surface p-4"><p className="text-mute">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p>{note&&<p className="mt-0.5 text-xs text-mute">{note}</p>}</div>
export const Bar=({pct,tone='accent'}:{pct:number;tone?:string})=><div className="h-1.5 rounded-full bg-line"><div className="h-full rounded-full" style={{width:pct+'%',background:`var(--${tone})`}}/></div>
export const Head=({title,sub}:{title:string;sub:string})=><div className="mb-5"><h1 className="text-2xl font-semibold tracking-tight">{title}</h1><p className="mt-1 text-mute">{sub}</p></div>
